Repository OCA/oca-addons-repo-template, pull requests merged in 2020-10, with the labels that each got.

#11 Warn more about manual updates to answers file
  {{ _copier_conf.answers_file }}.jinja
Labels: approved

#12 Mark modifiable zones in README.md and CONTRIBUTING.md
  CONTRIBUTING.md.jinja
  README.md.jinja
Labels: approved

#19 Update action versions
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: hacktoberfest-accepted

#17 Set language_version for prettier
  .pre-commit-config.yaml.jinja
Labels: hacktoberfest-accepted, needs review

#20 Remove pylint-odoo missing-import-error and missing-manifest-dependency checks
  .pylintrc-mandatory.jinja
  .pylintrc.jinja
Labels: needs review

#3 Add placeholder for exclude list of uninstallable addons
  .pre-commit-config.yaml.jinja
Labels: approved, ready to merge

#27 [ADD] add development-status-allowed check
  .pylintrc-mandatory.jinja
Labels: approved, needs review

#35 Use strict mode in prettier xml plugin
  .prettierrc.yml
Labels: enhancement, needs review

#29 Test python 3.6-3.8
  .github/workflows/test.yml
Labels: enhancement

#36 Pin node version for 13.0 too
  version-specific/13.0/.pre-commit-config.yaml
Labels: approved, needs review
