Repository OCA/oca-addons-repo-template, pull requests merged in 2021-11, with the labels that each got.

#88 [REM] Don't include CONTRIBUTING.md in the generated projects
  copier.yml
  src/CONTRIBUTING.md.jinja
  tests/test_copy.py
Labels: enhancement

#89 Fix pre-commit errors with black
  src/.github/workflows/pre-commit.yml.jinja
Labels: approved

#90 [IMP] run oca-gen-addon-readme in pre-commit
  src/.pre-commit-config.yaml.jinja
Labels: approved

#94 Revert "[IMP] run oca-gen-addon-readme in pre-commit"
  src/.pre-commit-config.yaml.jinja
Labels: needs review
