Repository OCA/oca-addons-repo-template, pull requests merged in 2022-03, with the labels that each got.

#130 [FIX] Do not run CI jobs twice on every commit
  src/.github/workflows/pre-commit.yml.jinja
  src/.github/workflows/{% if ci == 'GitHub' %}test.yml{% endif %}.jinja
Labels: approved

#122 [IMP] eslint: bump to escmascript 2019
  src/.eslintrc.yml
Labels: approved, ready to merge

#128 [FIX] pylint-odoo: usable under python 3.10
  src/.github/workflows/pre-commit.yml.jinja
  src/.pre-commit-config.yaml.jinja
Labels: bug, approved, ready to merge

#134 imp: Odoo <14.0: pin black click dependency to <8.1.0 - Odoo >=14.0: bump black to 22.3.0
  .pre-commit-config.yaml
  src/.pre-commit-config.yaml.jinja
  version-specific/13.0/.pre-commit-config.yaml
Labels: approved
